# test

In [3]:
import numpy as np

Z = np.zeros(10)
print(Z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [4]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [5]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [7]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [10]:
Z = np.eye(3)
print(Z)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [14]:
Z = np.random.random((3,3))
print(Z)

Z = np.random.random((3,2,3))
print(Z)

[[ 0.8529614   0.96976627  0.67719326]
 [ 0.49762619  0.21155705  0.1159439 ]
 [ 0.66925502  0.91887169  0.44388145]]
[[[ 0.69151888  0.3661391   0.68499587]
  [ 0.28193486  0.09265288  0.11873192]]

 [[ 0.85715107  0.05618417  0.05242522]
  [ 0.07471615  0.75280953  0.2933091 ]]

 [[ 0.84465851  0.58144629  0.54487298]
  [ 0.9615494   0.57405362  0.79752941]]]


In [15]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.000445528678486 0.998504807319
